//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectoProgra5.DBContext
{
    using System;
    
    public partial class SP_Listar_Productos_Result1
    {
        public int id { get; set; }
        public string Nombre_Producto { get; set; }
        public int PrecioUnidad { get; set; }
        public int Cantidad { get; set; }
        public int Marca_id { get; set; }
        public int Modelo_id { get; set; }
        public string Nombre_Marca { get; set; }
        public string Nombre_Modelo { get; set; }
    }
}
